name: Deploy 
on:
  push:
    branches:
      - main  # aca iria develop en Sodep
 
jobs:
  build-push-image:
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
      actions: read
 
    steps:
    # Generate the AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: 'arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_TO_PUSH_IMG }}'
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
    # Log In to the ECR repo
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Checkout code
      uses: actions/checkout@v4
    # Build and Push the Container Image
#   - name: Build, tag, and push image to Amazon ECR
    #  env:
     #   ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #  ECR_REPOSITORY: pruebas/nmontes # the ECR repo name
    #    IMAGE_TAG: test # The image tag, it could be the commit SHA: ${{ github.sha }}
     # run: |
      #  docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
       # docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
 
 
    - name: Build all services with docker compose
      run: docker compose build
 
    - name: List built images from docker compose
      id: list_images
      run: |
        docker images | awk 'NR>1 {print $1}' > images.txt
        echo "IMAGES<<EOF" >> $GITHUB_OUTPUT
        cat images.txt >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
###
 
    - name: Set image tag (short SHA)
      id: vars
      run: |
        set -euo pipefail
        IMAGE_TAG=$(git rev-parse --short HEAD)
        echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
        echo "image_tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT
        echo "Usando IMAGE_TAG=${IMAGE_TAG}"
 
    # Taguear y pushear todas las imágenes con el tag devX.Y.Z
    - name: Tag & Push images to ECR with dev tag
      run: |
        set -euo pipefail
 
        REGISTRY="652910315526.dkr.ecr.us-west-2.amazonaws.com"
        REPO="pruebas/nmontes"
        TAG="${{ env.IMAGE_TAG }}"
 
        echo "Usando registry: $REGISTRY"
        echo "Repositorio: $REPO"
        echo "Tag: $TAG"
 
        while read IMAGE; do
          [ -z "$IMAGE" ] && continue
 
          echo "Processing image: $IMAGE"
 
          # Tag remoto: un solo repo, tag por servicio + versión
          # ej: pruebas/nmontes:testdeploy-main-web-sha423646355
          REMOTE_IMAGE="$REGISTRY/$REPO:${IMAGE}-${TAG}"
 
          echo "Tagging $IMAGE → $REMOTE_IMAGE"
          docker tag "$IMAGE:latest" "$REMOTE_IMAGE"
 
          echo "Pushing $REMOTE_IMAGE"
          docker push "$REMOTE_IMAGE"
 
          echo "Done processing $IMAGE"
        done < images.txt