apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3-postgres
  namespace: comunidad  # not required, but allowed
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
reclaimPolicy: Retain
allowVolumeExpansion: true
# volumeBindingMode: WaitForFirstConsumer
