apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: comunidad
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: 701857162048.dkr.ecr.us-east-1.amazonaws.com/postgres:17  # Reemplaza con la imagen adecuada de ECR
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-db
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
              subPath: data  # Usar subPath para evitar que se sobreescriban los archivos previos en el volumen
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: gp3-postgres  # Asegúrate de que esta StorageClass esté configurada en tu EKS
        resources:
          requests:
            storage: 20Gi  # Tamaño del volumen de EBS (ajustar según necesidades)
